# Generated by Django 2.1.4 on 2018-12-14 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Montreapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pointvente',
            old_name='email',
            new_name='emaill',
        ),
        migrations.RenameField(
            model_name='pointvente',
            old_name='username',
            new_name='usernamee',
        ),
    ]
