# Generated by Django 2.1.1 on 2018-12-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Montreapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='slug',
            field=models.SlugField(default='simo', unique=True),
            preserve_default=False,
        ),
    ]
