# Generated by Django 2.1.1 on 2018-12-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Montreapp', '0002_produit_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='Description',
        ),
        migrations.AddField(
            model_name='produit',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
